[DEFAULT]

# Data location
data = /Users/stefanorinaldi/Documents/Sim/

# Output location
out = /Users/stefanorinaldi/Documents/Sim/

# Posterior samples file
post = /Users/stefanorinaldi/Documents/Sim/posterior_29_short.dat

# Classes: CBC, test
event_class = CBC

# Event number
event = None

# Cosmological model
model = LambdaCDM

# Catalog file
cat = /Users/stefanorinaldi/Documents/Sim/cat_test/mockcatalog.txt

# Electromagnetic counterpart
EMcp = 0

# Maximum number of events
nevmax = None

# threshold magnitude
m_th = 18.

# lower bound h prior
hmin = 0.5

# higher bound h prior
hmax = 1

# number of meshpoints
npoints = 8

# true h value
trueh = 0.697
